### ISSUE TITLE
kamcli db create fails for remote mysql database (with suggested fix)

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#14]
I installed from the nightly ubuntu focal packages.

Kamcli tries to create the same user twice and therefore aborts before creating the database.
I tracked the problem down:

The problem is in db_create_mysql_users ()
Located in /usr/lib/python3/dist-packages/kamcli/commands/cmd_db.py   around line 356
Where it says  if dbhost !=“localhost”
In the call to db_create_mysql_host_users,  dbhost should be replaced with the string “localhost”.

An additional problem then surfaced - the package installation is slightly broken.
kamcli looks for its files in /usr/local/share but they were installed to /usr/share
I added a symbolic link to get it working.

The following does what is required:

ln -s  /usr/share/kamailio    /usr/local/share/kamailio
ed /usr/lib/python3/dist-packages/kamcli/commands/cmd_db.py <<"EOT"
/def db_create_mysql_users/
/if dbhost != "localhost":/
/dbhost,/s/dbhost/"localhost"/
w
q
EOT

**Comment by Pcrossley69** [comment]
I've just rebuilt from git sources and it seems to have the same issue:
db_create_mysql_host_users() is called twice with the same parameters!

**Comment by miconda** [comment]
Closing this one as a commit was pushed for it a while ago (referenced above).
