### ISSUE TITLE
 kamcli acc rates-proc-create   fails with "not enough arguments for format string"

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#15]
kamcli acc rates-proc-create fails with "not enough arguments for format string"

I think I've found the trouble:

in    /usr/lib/python3/dist-packages/kamcli/commands/cmd_acc.py  line 395 
the code reads:
    WHERE rate_group=rgroup AND v_dst_username LIKE concat(prefix, '%')

Unfortunately python string formatting sees the % as a special character - replace it by %% and the sql command will be built correctly.

(does no-one test this stuff before packaging?)

**Comment by miconda** [comment]
Commit to address it has been pushed.
