### ISSUE TITLE
kamcli acc cdrs-generate   failing to commit cdrs update

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#16]
kamcli acc cdrs-generate fails to have any effect
I ran the stored procedure a different way and it works fine.

Looking at a packet trace, I can see that when kamcli is used the call  to the stored procedure is followed by a rollback.
I suspect there should be a commit before the rollback but haven't been able to find where this should be called from.

as a workaround I'm using:
   kamcli db clirun "call kamailio_cdrs()"

**Comment by Pcrossley69** [comment]
Unfortunately this still doesn't work
The packet trace now shows:
call kamailio_cdrs();
rollback;
commit;
rollback;

Consequently the changes are lost because of the rollback before the commit!

**Comment by miconda** [comment]
Pushed new changes to the git repo, can you try again with latest version?
