### ISSUE TITLE
"kamcli acc cdrs-generate" and "kamcli acc rates-generate" still  failing to commit changes (previously issue #16)

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#17]
"kamcli acc cdrs-generate" fails to have any effect:

kamcli db clirun "call kamailio_cdrs()"        works ok so the stored procedure is fine

Running a packet trace I can see that the sequence generated by  "kamcli acc cdrs-generate" is now:

call kamailio_cdrs();
rollback;
commit;
rollback;

Consequently the changes are lost because of the rollback before the commit!
The same issue affects "kamcli acc rates-generate"

**Comment by miconda** [comment]
Pushed changes to git repo, try and if still fails, reopen.
