### ISSUE TITLE
"kamcli acc rates-add"    fails with an SQL error (with suggested fix)

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#19]
This seems to be because the default table name hasn't been set.

It can be fixed by editing 
/usr/local/lib/python3.8/dist-packages/kamcli/commands/cmd_acc.py

Line 299

replace  default="", with  default="billing-rates"

Note: It would be useful to have a function that lists the billing rates
(at the moment I use        kamcli db clirun "select * from billing_rates")

**Comment by miconda** [comment]
Thanks, a commit has been pushed recently.
