### ISSUE TITLE
"kamcli acc rates generate" asks for a parameter but then wont accept one

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#20]
The correct syntax is         kamcli acc rates generate <group>
But it complains with or without the parameter.

NOTE: It seems to me that if different prefixes have different rates you should only call the procedure once.
           It should then loop through applying all the rates in the table.

It may be worth changing the stored procedure so that if called with no parameters it simply applies them all in turn.

There should also be another command to display the rates that have been defined.
   kamcli acc rates-list

**Comment by miconda** [comment]
Thanks! It should be fixed now.
