### ISSUE TITLE
kamcli rates add  - inline help for the kamailio shell doesn't work - it only describes the table parameter

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#21]
When using the kamcli shell  the user receives help in constructing the command.
The help for acc rates-add shows just the optional parameter --dbtname and gives no hint on the parameters that are actually required.

**Comment by miconda** [comment]
The options of the command have name and help, they are given in the pop-up help when constructing the command.

The (positional) arguments have only values, which cannot be suggested when writing the command.Also, the arguments have no help property that could be displayed, see:

  - https://click.palletsprojects.com/en/8.1.x/documentation/#documenting-arguments

One has to run the command with `-h` to see what arguments can be provided.

At this moment does not seem to be simple way to present the arguments when typing the command, if anyone has a solution, just make a PR with the enhancement.
