### ISSUE TITLE
Incompatibilitiy with latest python?        error:  'configparser' has no attribute 'SafeConfigParser'

### ISSUE THREAD

**Issue by Pcrossley69** [kamailio/kamcli#23]
I got this message at the end of the backtrace  while running "kamcli config install"
"AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?"

When researching it I found this:
"update versioneer command; SafeConfigParser and readfp no longer exist"

One contributor for a different product noted  
"I removed it [versioneer] and replaced it with setuptools_scm in the main branch"

I'm not a python expert but hopefully someone here will know what this means.

**Comment by miconda** [comment]
Provide version of Python and the operating system to know where/how to test.

**Comment by miconda** [comment]
Pushed the above referenced commit, based on the remarks from:

  - https://stackoverflow.com/questions/2848711/why-is-there-raw-safeconfigparser-in-python-3

The `ConfigParser()` seems to be the recommended replacement.
