### ISSUE TITLE
How to cut out unwanted metrics?

### ISSUE THREAD

**Issue by CzyerChen** [kamailio/kamcli#27]
Can you provide guidance on how to reduce the number of metrics after deployment and monitoring?

Now, in order to reduce the number of commands, some registration, session, and transaction metrics may not need to be collected.

Thanks!

**Comment by miconda** [comment]
The options are to get stats only for a group, like:

```
kamcli stats usrloc
```

or a single stat by name, like:

```
kamcli stats -s location_contacts
```

If you want to discuss more, use the sr-users@lists.kamailio.org mailing list.
