### ISSUE TITLE
Add console to simplify kamcli usage

### ISSUE THREAD

**Issue by mwolff44** [kamailio/kamcli#9]
As talked during the dev meeting in Dusserdolf, i will add a feature allowing to open a console when calling kamcli

**Comment by miconda** [comment]
OK, thanks, very appreciated!

**Comment by miconda** [comment]
Added by 5b603145098479749fe3b06af107018934a393c1 . Interactive shell is started with `kamcli shell`. If better alternative is found, just make a PR.
